site_name: "Representational spaces"
site_url: https://jvlab.github.io/rs-software/
repo_url: https://github.com/jvlab/rs-software
theme:
  name: material
  features:
    - toc.integrate 
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections

hooks:
  - docs/hook_site_config.py
  - docs/hooks.py
  - docs/hook_ignore.py
  - docs/hook_format_nested_args.py
  - docs/hook_strip_contents_docstring.py
  - docs/hook_collapse_details.py
  

watch:
  - src

plugins:
- search
- autolinks 
- autorefs
- mkdocstrings:
    default_handler: matlab
    handlers:
        matlab:
            #paths: [src] 
            paths_recursive: true 
            options:
                docstring_section_style: list
                show_root_heading: true
                show_signature: true
                separate_signature: false
                signature_crossrefs: false
                parse_arguments: true
                docstring_style: google
                
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
     
extra_css:
  - css/extra.css
  
  
nav:
  - Home: index.md
  - Creating RS from perceptual judgments:
    - Overview: rs-py-overview.md
    - Installation: rs-py-installation.md
    - Demos:
      - Demo 1 - Raw Rankings → Detailed Choice File: rs-py-demo1.md
      - Demo 2 - Detailed Choice File → Combined Choice File: rs-py-demo2.md
      - Demo 3 - Combined Choice File → Geometric model: rs-py-demo3.md
      - How to Run Scripts: rs-py-scripts.md
    - Function index: function-index-python.md 
  - Manipulating RS:
    - Overview: rs-ml-overview.md
    - Installation: rs-ml-installation.md
    - Demos (MATLAB): demos.md
    - Function index: function-index-matlab.md
  - File formats, data structures, and domains: 
    - File formats: file-formats.md
    - Data structures: data_structures.md
    - Domains: domains.md
  - Python - MATLAB/Octave: python-matlab-octave.md

not_in_nav: mfiles/*
