site_name: "Representational spaces"
site_url: https://jvlab.github.io/rs-software/
theme:
  name: material
  features:
    - toc.integrate 

hooks:
  - docs/hook_site_config.py
  - docs/hooks.py
  - docs/hook_ignore.py
  - docs/hook_format_nested_args.py
  - docs/hook_collapse_details.py

watch:
  - src

plugins:
- search
- autolinks 
- autorefs
- mkdocstrings:
    default_handler: matlab
    handlers:
        matlab:
            #paths: [src] 
            paths_recursive: true 
            options:
                docstring_section_style: list
                show_root_heading: true
                show_signature: true
                separate_signature: false
                signature_crossrefs: false
                parse_arguments: true
                docstring_style: google
                
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
     
extra_css:
  - css/extra.css
     
nav:
  - Home: index.md
  - Installation: installation.md
  - Modules: modules.md
  - Function index: function-index.md
  - Demos: demos.md
  - Data structures: data_structures.md

not_in_nav: mfiles/*
